{{- if .Values.memcached.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-app.fullname" . }}-memcached
  labels:
    {{- include "k8s-app.labels" . | nindent 4 }}
    app: memcached
spec:
  replicas: {{ .Values.memcached.replicas }}
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      labels:
        app: memcached
        project: {{ .Values.global.project }}
    spec:
      containers:
      - name: memcached
        image: "{{ .Values.memcached.image.repository }}:{{ .Values.memcached.image.tag }}"
        imagePullPolicy: {{ .Values.memcached.image.pullPolicy }}
        resources:
          {{- toYaml .Values.memcached.resources | nindent 10 }}
        ports:
        - containerPort: {{ .Values.memcached.service.port }}
{{- end }}