{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-app.fullname" . }}-mysql
  labels:
    {{- include "k8s-app.labels" . | nindent 4 }}
    app: mysql
spec:
  selector:
    app: mysql
  ports:
  - port: {{ .Values.mysql.service.port }}
    targetPort: {{ .Values.mysql.service.port }}
  type: {{ .Values.mysql.service.type }}
{{- end }}