{{- if .Values.mysql.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-app.fullname" . }}-mysql
  labels:
    {{- include "k8s-app.labels" . | nindent 4 }}
    app: mysql
spec:
  replicas: {{ .Values.mysql.replicas }}
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        project: {{ .Values.global.project }}
        app: mysql
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.mysql.service.port }}
          resources:
            {{- toYaml .Values.mysql.resources | nindent 12 }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "k8s-app.fullname" . }}-mysql-secret
                  key: MYSQL_ROOT_PASSWORD
          {{- if .Values.mysql.persistence.enabled }}
          volumeMounts:
            - name: mysql-pvc
              mountPath: /var/lib/mysql
          {{- end }}
      {{- if .Values.mysql.persistence.enabled }}
      volumes:
        - name: mysql-pvc
          persistentVolumeClaim:
            claimName: {{ include "k8s-app.fullname" . }}-mysql-pvc
      initContainers:
        - name: busybox
          image: busybox:latest
          volumeMounts:
            - name: mysql-pvc
              mountPath: /var/lib/mysql
          command: ["sh", "-c", "rm -rf /var/lib/mysql/lost+found"]
      {{- end }}
{{- end }}