{{- if .Values.tomcat.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-app.fullname" . }}-tomcat
  labels:
    {{- include "k8s-app.labels" . | nindent 4 }}
    app: tomcat
spec:
  selector:
    app: tomcat
  ports:
    - port: {{ .Values.tomcat.service.port }}
      targetPort: {{ .Values.tomcat.service.port }}
  type: {{ .Values.tomcat.service.type }}
{{- end }}